package com.servicios.app.posts

object PublicacionesData {
    val publicaciones = listOf(
        PublicacionServicio(
            id = 1,
            titulo = "Reparar computador portátil que no enciende",
            descripcion = "Mi MacBook Pro 2019 no enciende. Cuando lo conecto se escucha un click pero no arranca. Necesito diagnóstico y reparación.",
            categoria = "Tecnología",
            presupuesto = "$80.000 - $200.000",
            urgencia = Urgencia.HOY,
            direccion = "Chapinero Alto",
            ciudad = "Bogotá",
            fechaCreacion = "Hace 30 min",
            ofertasRecibidas = 3,
            estado = EstadoPublicacion.ACTIVA,
            autor = "Laura G.",
        ),
        PublicacionServicio(
            id = 2,
            titulo = "Arreglar chapa de puerta de entrada",
            descripcion = "La chapa de la puerta principal no abre bien, hay que mover la llave varias veces. Preferiblemente cerrajero con experiencia.",
            categoria = "Cerrajería",
            presupuesto = "$40.000 - $80.000",
            urgencia = Urgencia.ESTA_SEMANA,
            direccion = "La Candelaria",
            ciudad = "Bogotá",
            fechaCreacion = "Hace 2 horas",
            ofertasRecibidas = 5,
            estado = EstadoPublicacion.ACTIVA,
            autor = "Carlos P.",
        ),
        PublicacionServicio(
            id = 3,
            titulo = "Pintar sala, comedor y pasillo — 60 m²",
            descripcion = "Necesito pintar sala, comedor y pasillo de mi apartamento. Aproximadamente 60 m². Tengo la pintura, necesito mano de obra.",
            categoria = "Pintura",
            presupuesto = "$150.000 - $300.000",
            urgencia = Urgencia.ESTA_SEMANA,
            direccion = "Barrio Niza",
            ciudad = "Bogotá",
            fechaCreacion = "Ayer",
            ofertasRecibidas = 2,
            estado = EstadoPublicacion.ACTIVA,
            autor = "María R.",
        ),
        PublicacionServicio(
            id = 4,
            titulo = "Reparación tubería cocina — fuga de agua",
            descripcion = "Hay una fuga en la tubería debajo del fregadero. El agua está mojando el mueble. Necesito plomero urgente.",
            categoria = "Plomería",
            presupuesto = "$50.000 - $150.000",
            urgencia = Urgencia.URGENTE,
            direccion = "Usaquén",
            ciudad = "Bogotá",
            fechaCreacion = "Hace 10 min",
            ofertasRecibidas = 7,
            estado = EstadoPublicacion.ACTIVA,
            autor = "Ana S.",
        ),
    )
}
